theme: jekyll-theme-cayman
title: Blender Launcher
site_name: Blender Launcher
site_description: Standalone client for managing official builds of Blender 3D

toc:
  - title: Group 1
    subfolderitems:
      - page: Thing 1
        url: /index.md
      - page: Thing 2
        url: /index.md
      - page: Thing 3
        url: /index.md
  - title: Group 2
    subfolderitems:
      - page: Piece 1
        url: /index.md
      - page: Piece 2
        url: /index.md
      - page: Piece 3
        url: /index.md
  - title: Group 3
    subfolderitems:
      - page: Widget 1
        url: /index.md
      - page: Widget 2
        url: /index.md
      - page: Widget 3
        url: /index.md
