site_name: Blender Launcher
site_description: Standalone client for managing official builds of Blender 3D
nav:
    - Introduction: index.md
    - Installation: installation.md
    - Help: help.md
    - Troubleshooting: troubleshooting.md
    - Changelog: changelog.md
docs_dir: mkdocs
site_dir: docs
theme: readthedocs
markdown_extensions:
    - smarty
    - admonition
