site_name: Blender Launcher
site_description: Standalone client for managing official builds of Blender 3D
nav:
    - Home: index.md
    - Installation: installation.md
    - User Interface: user_interface.md
    - Library Folder: library_folder.md
    - Settings: settings.md
    - Troubleshooting: troubleshooting.md
    - Feature Request: feature_request.md
    - Development: development.md
    - Changelog: changelog.md
docs_dir: mkdocs
site_dir: site
theme:
    name: material
    palette:
        scheme: slate
        primary: blue
        accent: indigo
    features:
        - navigation.instant
        - search.suggest
        - search.highlight
    favicon: icons/favicon.svg
    logo: icons/favicon.svg
markdown_extensions:
    - smarty
    - admonition
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.details
    - attr_list
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - pymdownx.keys
    - def_list
    - pymdownx.critic:
        mode: view
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
        permalink: true
plugins:
  - search:
      lang: en
extra_css:
    - stylesheets/extra.css
repo_url: https://github.com/DotBow/Blender-Launcher
edit_uri: ""
copyright: Copyright &copy; 2021 Oleg Stepanov │ Blender Launcher GPL-3.0 License │ Version 1.14.0
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/dotbow
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/velvetdotbow
        - icon: fontawesome/brands/artstation
          link: https://www.artstation.com/dotbow
        - icon: fontawesome/solid/envelope
          link: mailto:stepanovoleg.dev@gmail.com
