site_name: Blender Launcher
site_description: Standalone client for managing official builds of Blender 3D
nav:
    - index.md
    - installation.md
    - user_interface.md
    - library_folder.md
    - settings.md
    - troubleshooting.md
    - development.md
    - feature_request.md
    - changelog.md
docs_dir: mkdocs
site_dir: site
theme:
    name: material
    palette:
        scheme: slate
        primary: blue
        accent: indigo
    features:
        - navigation.instant
    favicon: icons/favicon.svg
    logo: icons/favicon.svg
markdown_extensions:
    - smarty
    - admonition
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.details
    - attr_list
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - pymdownx.keys
    - def_list
    - pymdownx.critic:
        mode: view
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
        permalink: #
extra_css:
    - stylesheets/extra.css
repo_url: https://github.com/DotBow/Blender-Launcher
copyright: Copyright &copy; 2021 Oleg Stepanov │ Blender Launcher GPL-3.0 License
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/dotbow
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/velvetdotbow
        - icon: fontawesome/brands/artstation
          link: https://www.artstation.com/dotbow
        - icon: fontawesome/solid/paper-plane
          link: mailto:stepanovoleg.dev@gmail.com
