name: Windows Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.9'
      - name: Build
        run: |
          pip install pdm
          python -m pip install virtualenv
          python -m virtualenv --clear --download .venv
          python -m ensurepip
          python -m pip install --upgrade pdm
          pdm venv activate
          pdm install
          python build_style.py
          .\build_win.bat
      - name: Zipping
        run: |
          echo "Zipping to Blender_Launcher_${{ env.RELEASE_VERSION }}_Windows_x64.zip"
          cd ./dist/release/
          zip Blender_Launcher_${{ env.RELEASE_VERSION }}_Windows_x64.zip "./Blender Launcher"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/release/Blender_Launcher_${{ env.RELEASE_VERSION }}_Windows_x64.zip
